name: Deploy PHP code to an FTP destination

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  deploy:
    name: Deploy the application to ftp destination
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Install PHPUnit
        run: composer require --dev phpunit/phpunit
      - name: Show
        run: ls  
      - name: Run tests
        run: |
          vendor/bin/phpunit tests/taskTest.php
      - name: Sync file with the hosting
        uses: Samkirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
